apiVersion: apps/v1
kind: Deployment
metadata:
  name: datahub-gms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datahub-gms
  template:
    metadata:
      labels:
        app: datahub-gms
    spec:
      containers:
      - name: datahub-gms
        image: linkedin/datahub-gms:latest
        env:
        - name: DATAHUB_GMS_ELASTICSEARCH_HOST
          value: elasticsearch-host
        - name: DATAHUB_GMS_ELASTICSEARCH_PORT
          value: "9200"
        - name: DATAHUB_GMS_MYSQL_HOST
          value: mysql-host
        - name: DATAHUB_GMS_MYSQL_PORT
          value: "3306"
        - name: DATAHUB_GMS_MYSQL_USERNAME
          value: mysql-user
        - name: DATAHUB_GMS_MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: mysql-password
        ports:
        - containerPort: 8080
