apiVersion: apps/v1
kind: Deployment
metadata:
  name: datahub-gms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datahub-gms
  template:
    metadata:
      labels:
        app: datahub-gms
    spec:
      containers:
      - name: datahub-gms
        image: linkedin/datahub-gms:head
        env:
        - name: DATAHUB_GMS_ELASTICSEARCH_HOST
          value: elasticsearch-host
        - name: DATAHUB_GMS_ELASTICSEARCH_PORT
          value: "9200"
        - name: DATAHUB_GMS_POSTGRES_HOST
          value: datahub
        - name: DATAHUB_GMS_POSTGRES_PORT
          value: "5432"
        - name: DATAHUB_GMS_POSTGRES_USERNAME
          value: datahub
        - name: DATAHUB_GMS_POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: datahub
        ports:
        - containerPort: 8080

