apiVersion: v1
kind: Service
metadata:
  name: datahub-gms
  labels:
    app: datahub-gms
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: datahub-gms
    type: ClusterIp
---
apiVersion: v1
kind: Service
metadata:
  name: datahub-frontend
  labels:
    app: datahub-frontend
spec:
  ports:
  - port: 9002
    name: http
  selector:
    app: datahub-frontend
    type: LoadBalancer
