apiVersion: v1
kind: Service
metadata:
  name: datahub-gms
  labels:
    app: datahub-gms
spec:
  type: ClusterIP
  ports:
  - port: 8080
    name: http
  selector:
    app: datahub-gms
---
apiVersion: v1
kind: Service
metadata:
  name: datahub-frontend
  labels:
    app: datahub-frontend
spec:
  type: LoadBalancer
  ports:
  - port: 9002
    name: http
  selector:
    app: datahub-frontend
